name: Deploy to GitHub Pages

on:
  push:
    branches: [master] # 或 master，取决于你的默认分支

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 21
      
      - name: Install dependencies
        run: npm install
      
      - name: Build
        run: npm run docs:build

      - name: List dist directory contents  # 调试步骤，确认 dist 目录是否存在且有文件
        run: ls -la .vitepress/dist

      - name: List all files in dist directory
        run: find .vitepress/dist

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .vitepress/dist
